[package]
name = "advanced_types"
version = "0.1.0"
authors = ["AJTJ <janke.aaron@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "0.8", features = ["v4"]}
